INSERT INTO bears ('Mr. Chocolate', 12, 'M', 'brown', 'angry', 'true')
INSERT INTO ('Rowdy', 10, 'F', 'purple', 'happy', 'true')
INSERT INTO ('Tabitha', 5, 'M', 'brown', 'angry', 'true')
INSERT INTO ('Sergeant Brown', 8, 'F', 'black', 'unfettered', 'true')
INSERT INTO ('Melissa', 2, 'M', 'orange', 'excited', 'true')
INSERT INTO ('Grinch', 3, 'F', 'white', 'silly', 'true')
INSERT INTO ('Wendy', 9, 'M', 'white and black', 'ashamed', 'false')
INSERT INTO (nil, 2, 'F', 'calico', 'stoked', 'false')
