INSERT INTO bears ('Mr. Chocolate', "12", 'M', 'brown', 'angry', 'true')
INSERT INTO bears ('Rowdy', 10, 'F', 'purple', 'happy', 'true')
INSERT INTO bears ('Tabitha', 5, 'M', 'brown', 'angry', 'true')
INSERT INTO bears ('Sergeant Brown', 8, 'F', 'black', 'unfettered', 'true')
INSERT INTO bears ('Melissa', 2, 'M', 'orange', 'excited', 'true')
INSERT INTO bears ('Grinch', 3, 'F', 'white', 'silly', 'true')
INSERT INTO bears ('Wendy', 9, 'M', 'white and black', 'ashamed', 'false')
INSERT INTO bears (nil, 2, 'F', 'calico', 'stoked', 'false')
